apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: {{ .Values.image }}
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"  
            cpu: "250m"       
          limits:
            memory: "256Mi"
            cpu: "500m"
